#!/bin/bash
# Build cuOpt from source inside Docker.
# Called by Dockerfile.build — avoids cmake-args quoting issues in RUN strings.
set -eo pipefail

# conda env 存在時啟動（conda build），否則為官方 image 環境（pip build）
if [ -f /opt/conda/etc/profile.d/conda.sh ]; then
    source /opt/conda/etc/profile.d/conda.sh
    conda activate /opt/cuopt_env
fi

# 官方 image 環境：把 RAPIDS_DIST 下的 cmake 路徑轉成 cmake 分號分隔格式
if [ -n "${RAPIDS_DIST:-}" ]; then
    # CUDA stubs 讓 cmake 找到 CUDA::cublas 等 targets 而不需要安裝完整的 -dev 套件
    # 實際執行時 libcublas 由 cuopt pip packages 的 .libs 目錄提供
    export CMAKE_LIBRARY_PATH="/usr/local/cuda/targets/x86_64-linux/lib/stubs:${CMAKE_LIBRARY_PATH:-}"


    # cmake 從 env var 讀 CMAKE_PREFIX_PATH 時使用 Unix PATH 格式（冒號分隔）
    # 支援兩種路徑結構：
    #   pip 安裝（舊方式）：RAPIDS_DIST=/usr/local/lib/python3.x/dist-packages
    #   COPY 方式（新方式）：RAPIDS_DIST=/opt/rapids
    export CMAKE_PREFIX_PATH="\
${RAPIDS_DIST}/libcuopt/lib64/rapids/cmake:\
${RAPIDS_DIST}/libraft/lib64/rapids/cmake:\
${RAPIDS_DIST}/librmm/lib64/rapids/cmake:\
${RAPIDS_DIST}/libcuopt/lib64/cmake:\
${RAPIDS_DIST}/libraft/lib64/cmake:\
${RAPIDS_DIST}/librmm/lib64/cmake:\
${RAPIDS_DIST}/rapids_logger/lib64/cmake:\
${RAPIDS_DIST}/libcuopt/lib64:\
${RAPIDS_DIST}/libraft/lib64:\
${RAPIDS_DIST}/librmm/lib64:\
${RAPIDS_DIST}"
    echo "CMAKE_PREFIX_PATH set for official image environment"
fi

# 預先 clone 的 FetchContent 依賴（離線 build 用）
export FETCHCONTENT_SOURCE_DIR_PAPILO="${FETCHCONTENT_SOURCE_DIR_PAPILO:-/opt/cuopt-deps/papilo}"
export FETCHCONTENT_SOURCE_DIR_PSLP="${FETCHCONTENT_SOURCE_DIR_PSLP:-/opt/cuopt-deps/pslp}"
export FETCHCONTENT_SOURCE_DIR_ARGPARSE="${FETCHCONTENT_SOURCE_DIR_ARGPARSE:-/opt/cuopt-deps/argparse}"

# build.sh 硬寫 'python'，但部分容器只有 'python3' → 建立暫時 shim
if ! command -v python &>/dev/null && command -v python3 &>/dev/null; then
    mkdir -p /tmp/py-shim
    ln -sf "$(command -v python3)" /tmp/py-shim/python
    export PATH="/tmp/py-shim:${PATH}"
fi

# Ubuntu 24.04 PEP 668：允許 pip 安裝到 system Python（開發容器環境）
export PIP_BREAK_SYSTEM_PACKAGES=1

# Python wheel build 需要的 build tools（--no-build-isolation 不自動安裝）
python3 -m pip install --quiet \
    "rapids-build-backend>=0.4.0,<0.5.0" \
    "scikit-build-core[pyproject]>=0.11.0" \
    "cython>=3.0.3" \
    "ninja"

export CUDACXX="$(which nvcc)"
export PARALLEL_LEVEL="${PARALLEL_LEVEL:-1}"

echo "=== cuOpt build ==="
echo "CUDACXX        : ${CUDACXX}"
echo "PARALLEL_LEVEL : ${PARALLEL_LEVEL}"
echo ""

# CUOPT_BUILD_ARCHS 控制編譯的 GPU 架構：
#   未設定（預設）→ NATIVE：docker run --gpus all 時自動偵測本機 GPU（最快）
#   "deploy"     → RAPIDS：所有架構（sm_70~sm_120），部署用，--allgpuarch
# Dockerfile.build 設定 CUOPT_BUILD_ARCHS=deploy 以取得完整架構支援
if [ "${CUOPT_BUILD_ARCHS:-native}" = "deploy" ]; then
    echo "CUDA 架構 : RAPIDS 全架構（sm_70/75/80/86/90a/100f/120a/120）"
    ARCH_FLAG="--allgpuarch"
else
    echo "CUDA 架構 : NATIVE（自動偵測本機 GPU，dev 容器最快）"
    ARCH_FLAG=""
fi
echo ""

# 官方 image 環境需要 --no-fetch-rapids（rapids-cmake 已在 image 中）
# 和 --skip-grpc-build（gRPC 離線無法下載）
if [ -n "${RAPIDS_DIST:-}" ]; then
    EXTRA_FLAGS="--no-fetch-rapids --skip-grpc-build"
else
    EXTRA_FLAGS=""
fi

if [ -n "${RAPIDS_DIST:-}" ]; then
    # ─── 兩步驟 build（官方 image 環境）───────────────────────────────────────
    # Step 1：只 build C++ library（libcuopt target）
    ./build.sh libcuopt ${ARCH_FLAG} ${EXTRA_FLAGS} --skip-tests-build "$@"

    # Step 2：把剛 build 的 libcuopt.so 放到 RAPIDS_DIST 讓 cmake config 找得到
    cp cpp/build/libcuopt.so "${RAPIDS_DIST}/libcuopt/lib64/"
    echo "libcuopt.so → ${RAPIDS_DIST}/libcuopt/lib64/ ✓"

    # Step 2a：官方 image 的 raft cmake targets 引用 /usr/lib64/libcudss/12/libcudss.so.0
    # apt 安裝的路徑是 /usr/lib/x86_64-linux-gnu/libcudss/...
    # 建立 symlink 讓 ninja 能找到
    if [ ! -f /usr/lib64/libcudss/12/libcudss.so.0 ]; then
        mkdir -p /usr/lib64/libcudss/12
        ln -sf /usr/lib/x86_64-linux-gnu/libcudss/12/libcudss.so.0 /usr/lib64/libcudss/12/libcudss.so.0
        echo "cudss symlink created ✓"
    fi

    # Step 2b：patch cmake install 產生的 cuopt-dependencies.cmake
    # rapids_export 只生成部分 find_dependency；補上 Python wheel 需要的 rmm/raft/CCCL
    DEPS_FILE=$(find /usr/lib/cmake/cuopt /lib/cmake/cuopt -name "cuopt-dependencies.cmake" 2>/dev/null | head -1)
    if [ -n "${DEPS_FILE}" ]; then
        cat >> "${DEPS_FILE}" << 'DEPS_EOF'

# Missing RAPIDS dependencies (not auto-generated by rapids_export in pip build)
find_dependency(rmm)
find_dependency(raft)
DEPS_EOF
        echo "Patched ${DEPS_FILE} with rmm/raft deps ✓"
    fi

    # Python wheel build 需要 pylibraft / rmm Cython 定義（.pxd），
    # 這些套件未在 dev image 中安裝。Python 測試請使用 run_test_py.sh：
    # 以官方 nvidia/cuopt image（已有 pylibraft/rmm/cupy）+ 自訂 libcuopt.so 掛載
    echo ""
    echo "=== C++ build complete ==="
    echo "  libcuopt.so  : cpp/build/libcuopt.so"
    echo "  cuopt_cli    : cpp/build/cuopt_cli"
    echo ""
    echo "  Python 測試請使用官方 image + custom .so："
    echo "  bash run_test_py.sh                    # pytest"
    echo "  bash run_test_py.sh ctest -j4          # C++ tests"
    echo ""
else
    ./build.sh ${ARCH_FLAG} ${EXTRA_FLAGS} --skip-tests-build "$@"
fi
